// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmyDe3F-5qM2MsgFwU8-34dzhO3IUDJk4',
    appId: '1:642128024383:web:4b676d0d1358765247798a',
    messagingSenderId: '642128024383',
    projectId: 'mimo-bf682',
    authDomain: 'mimo-bf682.firebaseapp.com',
    storageBucket: 'mimo-bf682.firebasestorage.app',
    measurementId: 'G-FM40YZQRBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA0CsYnipXOOLOFbgVB41ww0_tZ7c9bV8',
    appId: '1:642128024383:android:858cee11db29880647798a',
    messagingSenderId: '642128024383',
    projectId: 'mimo-bf682',
    storageBucket: 'mimo-bf682.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQQpp3xQZM6bR1ZzDgd799dAODhZwjwWs',
    appId: '1:642128024383:ios:fba789f0a828c97147798a',
    messagingSenderId: '642128024383',
    projectId: 'mimo-bf682',
    storageBucket: 'mimo-bf682.firebasestorage.app',
    iosBundleId: 'com.example.mimo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQQpp3xQZM6bR1ZzDgd799dAODhZwjwWs',
    appId: '1:642128024383:ios:fba789f0a828c97147798a',
    messagingSenderId: '642128024383',
    projectId: 'mimo-bf682',
    storageBucket: 'mimo-bf682.firebasestorage.app',
    iosBundleId: 'com.example.mimo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmyDe3F-5qM2MsgFwU8-34dzhO3IUDJk4',
    appId: '1:642128024383:web:048f0a55981efb3e47798a',
    messagingSenderId: '642128024383',
    projectId: 'mimo-bf682',
    authDomain: 'mimo-bf682.firebaseapp.com',
    storageBucket: 'mimo-bf682.firebasestorage.app',
    measurementId: 'G-FNM5PMCRF0',
  );
}
